ROOT=../../..
COMMON=../..
EDDIE=..
#
OBJS=ABintegrator.o
NAME=continua/eddie/integrator
DEPS=output parser constants continua/common

include $(EDDIE)/Makefile.inc
include $(COMMON)/Makefile.inc
include $(ROOT)/Makefile.inc
