#!/bin/bash
# build charmm
export OPENMM_DIR=$OPENMM_HOME/lib

pushd charmm
patch -p1 < ../c47b2-omm-dynamo.patch

./configure --with-openmm --with-dynamo --without-mkl \
 -D DYNAMO_LIBRARY_DIR=~/projects/lib \
 --prefix=../omm-dynamo \

 #-D CMAKE_FIND_DEBUG_MODE=ON \

pushd build/cmake
make -j12
make install
popd

popd
