#!/bin/bash
#extract keywords from source code file for documentation
#
#grep "keyword*\.eq.\*\'*\'" \
#sm0k.src
grep -e "keyword.*\.eq\." -e "comlyn.*'.*" sm0k.src | awk ' { \
i = index($0,"\047"); \
cmd=substr($0,i+1); \
j = index(cmd,"\047"); \
keyword=substr(cmd,1,j-1);\
print "["keyword"]" ;\
}'
