#!/bin/bash

lib=~/scripts/
clib=$lib/charmm

name=alad
charmm=c45b1str
python=python
vmd=vmd

if [ 1 -eq 1 ]; then
# solvate in a cubic box if needed
ln -s ../$name.psf
ln -s ../${name}_m.cor
$charmm -i $clib/boxsolv.inp psffile=$name corfile=${name}_m maxdist=7 method=shell radoccu=0 -o solvate.out 
# ^ do not copy radius if this charmm version does not support it
$vmd -dispdev text < mkmass.vmd ;# mass file for dasystat
#exit
# equilibrate
export OMP_NUM_THREADS=5
python < equil.py >& equil.out
exit
fi

# run string simulations
nohup ./driver
