#!/bin/bash
# openMP variables
export OMP_NUM_THREADS=5
export OMP_SCHEDULE=STATIC
export OMP_NESTED=FALSE

mkdir -p data

pythoncmd=python2

brep=0
erep=7
stringfile="diala22_smcv_ini.txt"

for irep in `seq $brep $erep`; do
# prepare input file from template
#
  config=${irep}.in
  output=${irep}.out
  pluginfile=diala.smcv${irep}
  pluginout=${pluginfile}.out

  kf=200 # force constant

  cat template.smcv | \
  sed "s/@{stringfile}/$stringfile/g" | \
  sed "s/@{kf}/$kf/g" | \
  sed "s/@{irep}/$irep/g" | \
  sed "s/@{datadir}/data/g" | \
  cat > $pluginfile

  cat template.py |\
   sed "s/@{coordinates}/data\/diala22_zts_$irep.pdb/g" | \
   sed "s/@{input}/$pluginfile/g" | \
   sed "s/@{log}/$pluginout/g" | \
   sed "s/@{irep}/$irep/g" | \
   sed "s/@{restart}/0/g" | \
   sed "s/@{nsteps}/500000/g" | \
   sed "s/@{freq}/10000/g" | \
   cat > $config

  echo " ===> Running replica #$irep ..."
  $pythoncmd $config > $output
#
#exit
done
