% compute free energy from histogram generated by TAMD
%
close all;

nrun=5;
cvhist=load('deca_tamd_cv1.dat');
for i=2:nrun
 cvhist=[cvhist ; load(['deca_tamd_cv',num2str(i),'.dat'])];
end

temp=6000;
kb=1.98719e-3;

x0=12 ;
x1=32 ;
dx=1.  ;

x=x0:dx:x1 ;

[nn,x]=hist(cvhist,x) ;

fe = - kb * temp * log(nn); fe=fe-min(fe) ;

plot(x,fe,'ro-') ; hold on ; 
%pause(1000)

