! **********************************************************************!
! This source file was was generated automatically, (specifically for   !
! CHARMM) from a master source code tree, using a preprocessor.         !
! If you edit this file (rather than the master source file)            !
! your changes will be lost if another pull from the master tree occurs.!
! In case you are wondering why, this approach makes it possible for    !
! me to have the same master source code interfaced with different      !
! applications (some of which are written in a way that is quite far    !
! from being object-oriented) at the source level.                      !
! **********************************************************************!
