# recipes to create directory with string method code for charmm 39
# this directory contains "stringm", which has a Makefile to generate .src files and a patching script
# the user will put this directory into the charmm tree, run "make" to generate the .src files
# and run the "patch_xx.sh" script.  After these steps the CHARMM installation proceeds as usual;
# the keyword STRINGM must be added to the parameter line to install.com
#
SHELL=/bin/sh
CHARMM_VERSION=39a2
CHARMM_DISTRIB_DIR=$(addprefix c,$(CHARMM_VERSION))
CHARMM_DISTRIB_SRC=$(addsuffix /source, $(CHARMM_DISTRIB_DIR))

OUT=> 
BREAK====================================================================================

CHARMM_DIRS=bestfit vectors lu multicom multidiag confcons parselist string/ftsm string/sm0k string/smcv

charmm_string: charmm_distrib
charmm_distrib: charmm_patch
cpatch: charmm_patch
charmm_patch:
	echo $(BREAK)
	echo '$(OUT) Will prepare string source code package for CHARMM version $(CHARMM_VERSION)'
	echo '$(OUT) Creating directory "$(CHARMM_DISTRIB_DIR)"'
#create string directory
	mkdir -p $(CHARMM_DISTRIB_SRC)/stringm
#create subdirectories and copy files
	for d in $(CHARMM_DIRS); do \
	(locald=$${d##*/} ; echo $$locald; mkdir -p $(CHARMM_DISTRIB_DIR)/source/stringm/$$locald);\
	done
        


	
#.SILENT: charmm_patch message
	