#!/bin/bash
# script to make an archive of the charmm in this directory
# used in case git cloning is not an option
files=( *.def *.defs *.inc *.msg Makefile* )
dirs=( driver state bestfit constants dynamol erf files lu multicom multidiag output parselist parser random string timer vectors \
confcons enm continua pnm mpi_stub unitcell watershell plugin_master griddata adaptive )

tar -czvhf projects$(date +%F).tgz --exclude='*.o'  --exclude='.gitignore' --exclude='*.mod' --exclude='*.a' --exclude='*.so' --exclude='*.F90' --exclude='*.dcd' \
 --exclude='*.stamp' --exclude='*.out' --exclude='bkp' --exclude='*.tmp' --exclude='dbg' --exclude='*.dat' --exclude='*.pdb' --exclude='*.cor' --exclude='*.psf'  \
 --exclude='*.tgz' \
 ${files[@]} ${dirs[@]} 
