#!/bin/sh

log=update_log
echo -n > $log

file=$1

 sed -e 's/integer/int/g' \
     -e 's/real\*8/float/g' \
     -e 's/int\*4/int4mpi/g' \
     -e 's/logical/bool/g' \
     -e 's/character\*/character(len=/g' \
     -e 's/##/__CHARMM_ONLY##/g' \
     -e 's/use mpi/__DEP_MPI/g'\
     -e 's/use multicom_ltm/__DEP_MULTICOM/g'\
     -e 's/cv_base/cv_common/g'\
     -e 's/call wrndie(0,/__WRN(/g'\
     -e 's/use string/__DEP_OUTPUT/g'\
     -e 's/use mpi/__DEP_MPI/g'\
     -e 's/use stream/__DEP_PARSER/g'\
     -e 's/use consta/__DEP_CONST/g'\
     -e 's/use multicom_ltm/__DEP_MULTICOM/g'\
     -e 's/use bestfit/__DEP_BESTFIT/g'\
     -e 's/indxa/__INDX_RM/g'\
     -e 's/eqstwc/__STRNCMP/g'\
     -e 's/gtrmwd/__GET_RM_A/g'\
 < $file > temp.f
 if [ -f temp.f ]; then 
  diff $file temp.f --side-by-side --suppress-common-lines >> $log
  mv -f temp.f ${file%%.*}.ftn
 fi
 

