#!/bin/bash
toppar=~/charmm/parameters/c36
~/scripts/mergepar $toppar/par_all36_prot.prm $toppar/toppar_water_ions.str
~/scripts/mergetop $toppar/top_all36_prot.rtf $toppar/toppar_water_ions.str
mv mergepar.par alad36w.par
mv mergetop.top alad36w.top

# comment some nbfixes
sed -Ei 's/SOD\s+O/!SOD\tO/' alad36w.par