#!/bin/bash
# wrapper to prepare psf coordinates and parameters for acemd run of rab
charmm=charmm_repo
toppar="/home/surgeon/charmm/parameters/c36"
# make parameter file
./mergepar ${toppar}/par_all36_prot.prm ${toppar}/par_all36_na.prm ${toppar}/stream/toppar_all36_na_nad_ppi.str ${toppar}/toppar_water_ions.str 
# make list of ftsm atom indices
vmd -dispdev text < alist.vmd
# make coordinates and psf
mkdir -p scratch
mpirun -np 32 --bind-to none  $charmm -i mkacemd.inp -o mkacemd.out
