#!/bin/bash 
echo localhost > ~/nodes

namd=namd2.13d ;
cores=4;
# simulation parameters

d0=12 ;
d1=32 ;

fbw=1

nwin=32 ;


for i in `seq 22 $nwin`; do
#i=22; # to hard wire a run

  d=`echo "scale=2 ; $d0 + ( $d1 - $d0 ) * ( $i - 1 ) / ( $nwin - 1 ) " |bc -l`

# RUN SIMULATION
####################
  echo "Running window (d = $d) ..."
#
# prepare input file from template
#
  flag=${d}
# string file :
  cat template.sm | \
  sed "s/@fbw/$fbw/g" | \
  sed "s/@dref/$d/g" | \
  sed "s/@phi/$myphi/g" | \
  sed "s/@psi/$mypsi/g" | \
  sed "s/@fbw/$fbwrad/g" > deca${flag}.smcv
# simulation file :
  cat template |\
   sed "s/@nrun/$i/g" |\
   sed "s/@nprev/$((i-1))/g" |\
   sed "s/@smconfig/deca${flag}.smcv/g" |\
   sed "s/@smlog/deca${flag}.smcv.log/g" |\
   cat > deca.in

#  $charmrun +p${cores} 
  $namd +p${cores} deca.in > deca${flag}.out

#exit
done

