#!/bin/bash

source struna.sh

temprex0=298
temprex1=198
dtemprex=5 ; # temp increment/decrement

firstrun=1
numrun=500

lastrun=$((firstrun+numrun-1))
temprex=$temprex0

for irun in `seq $firstrun $lastrun`; do 

  echo -n " $temprex"

  xdir=`sm_rex_dir`

  temprex=`calc "if ($temprex1 > $temprex0) { t = min($temprex1, $temprex + abs($dtemprex)) } else { t = max($temprex1, $temprex - abs($dtemprex)) } ; print t"`

done
