#!/bin/bash
# preprocessing script to facilitate transforming the DYNAMO plugin into the DYNAMO plugin

sedcmd='s/struna/dynamo/g ; s/Struna/Dynamo/g ; s/STRUNA/DYNAMO/g'

dynamo_dir=openmm-dynamo


function replace_struna_with_dynamo() {
# change into a subdirectory passed as $1
# loop over all files and directories and
# replace "struna" with "dynamo" in all
# relevant capitalization instances;
# if a directory is encountered, call onself
# recursively
  d=$1
  if [ ! -d $d ]; then
   echo " ERROR : \"$d\" is not a directory. Abort."
  else
   echo " Descending into directory \"$d\" ..."
   pushd $d >&/dev/null
   for f in * ; do
    if [ -f $f ]; then
     echo "  Processing file \"$f\" ..."
     sed "$sedcmd" -i $f
# check and modify file name if necessary
     fnew=`echo $f | sed "$sedcmd"`
     echo " Moving \"$f\" ==> \"$fnew\" ..."
     mv -f $f $fnew
    elif [ -d $f ]; then
     replace_struna_with_dynamo $f
    fi
   done
   popd >& /dev/null
  fi
}

replace_struna_with_dynamo $dynamo_dir

