#!/bin/bash
# remove extraneous text from string file so we can read it into matlab
i=55;
sfile="../ftsm_string$i.txt"; # initial path from zts

temp='string.dat';
grep "^\sr[f,o]" $sfile | awk '{print $2" "$3" "$4}' > $temp
