#!/bin/bash
# preprocessing script to facilitate transforming the PLUMEd plugin into the STRUNA plugin

sedcmd='s/plumed/struna/g ; s/Plumed/Struna/g ; s/PLUMED/STRUNA/g ; s/Contributors\:/Contributors\:\ V\.\ Ovchinnikov/g'

plumed_dir=openmm-plumed


function replace_plumed_with_struna() {
# change into a subdirectory passed as $1
# loop over all files and directories and
# replace "plumed" with "struna" in all
# relevant capitalization instances;
# if a directory is encountered, call onself
# recursively
  d=$1
  if [ ! -d $d ]; then
   echo " ERROR : \"$d\" is not a directory. Abort."
  else
   echo " Descending into directory \"$d\" ..."
   pushd $d >&/dev/null
   for f in * ; do
    if [ -f $f ]; then
     echo "  Processing file \"$f\" ..."
     sed "$sedcmd" -i $f
# check and modify file name if necessary
     fnew=`echo $f | sed "$sedcmd"`
     echo " Moving \"$f\" ==> \"$fnew\" ..."
     mv -f $f $fnew
    elif [ -d $f ]; then
     replace_plumed_with_struna $f
    fi
   done
   popd >& /dev/null
  fi
}

replace_plumed_with_struna $plumed_dir

