# stringm makefile generated by tool/setmk.com
# stringm library rules
OBJS_stringm = cv_angle_com.o cv_anglvec.o cv_base.o cv_cvrms.o cv_dihe_com.o cv_dist_com.o cv_drmsd.o cv_frames.o \
    cv_posi_com.o cv_proj.o cv_qcomp.o cv_quaternion.o cv_rmsd.o cv_types.o ftsm.o ftsm_rex.o \
    ftsm_var.o ivector.o ivector_list.o parser.o sm0k.o sm_config.o sm_main.o sm_util.o \
    smcv.o smcv_add.o smcv_master.o smcv_var.o splines.o

$(LIB)/stringm.a : $(OBJS_stringm)
	$(AR_COMMAND) $(LIB)/stringm.a $(OBJS_stringm)
	$(RANLIB) $(LIB)/stringm.a
	@echo stringm COMPLETED

# stringm source file rules
cv_angle_com.o : $(SRC)/stringm/cv_angle_com.src
	$(FLX) $(SRC)/stringm/cv_angle_com.src
	$(FC2) cv_angle_com.f90
	$(REMOVE_F) cv_angle_com.f90

cv_anglvec.o : $(SRC)/stringm/cv_anglvec.src
	$(FLX) $(SRC)/stringm/cv_anglvec.src
	$(FC2) cv_anglvec.f90
	$(REMOVE_F) cv_anglvec.f90

cv_base.o : $(SRC)/stringm/cv_base.src
	$(FLX) $(SRC)/stringm/cv_base.src
	$(FC2) cv_base.f90
	$(REMOVE_F) cv_base.f90

cv_cvrms.o : $(SRC)/stringm/cv_cvrms.src
	$(FLX) $(SRC)/stringm/cv_cvrms.src
	$(FC2) cv_cvrms.f90
	$(REMOVE_F) cv_cvrms.f90

cv_dihe_com.o : $(SRC)/stringm/cv_dihe_com.src
	$(FLX) $(SRC)/stringm/cv_dihe_com.src
	$(FC2) cv_dihe_com.f90
	$(REMOVE_F) cv_dihe_com.f90

cv_dist_com.o : $(SRC)/stringm/cv_dist_com.src
	$(FLX) $(SRC)/stringm/cv_dist_com.src
	$(FC2) cv_dist_com.f90
	$(REMOVE_F) cv_dist_com.f90

cv_drmsd.o : $(SRC)/stringm/cv_drmsd.src
	$(FLX) $(SRC)/stringm/cv_drmsd.src
	$(FC2) cv_drmsd.f90
	$(REMOVE_F) cv_drmsd.f90

cv_frames.o : $(SRC)/stringm/cv_frames.src
	$(FLX) $(SRC)/stringm/cv_frames.src
	$(FC2) cv_frames.f90
	$(REMOVE_F) cv_frames.f90

cv_posi_com.o : $(SRC)/stringm/cv_posi_com.src
	$(FLX) $(SRC)/stringm/cv_posi_com.src
	$(FC2) cv_posi_com.f90
	$(REMOVE_F) cv_posi_com.f90

cv_proj.o : $(SRC)/stringm/cv_proj.src
	$(FLX) $(SRC)/stringm/cv_proj.src
	$(FC2) cv_proj.f90
	$(REMOVE_F) cv_proj.f90

cv_qcomp.o : $(SRC)/stringm/cv_qcomp.src
	$(FLX) $(SRC)/stringm/cv_qcomp.src
	$(FC2) cv_qcomp.f90
	$(REMOVE_F) cv_qcomp.f90

cv_quaternion.o : $(SRC)/stringm/cv_quaternion.src
	$(FLX) $(SRC)/stringm/cv_quaternion.src
	$(FC2) cv_quaternion.f90
	$(REMOVE_F) cv_quaternion.f90

cv_rmsd.o : $(SRC)/stringm/cv_rmsd.src
	$(FLX) $(SRC)/stringm/cv_rmsd.src
	$(FC2) cv_rmsd.f90
	$(REMOVE_F) cv_rmsd.f90

cv_types.o : $(SRC)/stringm/cv_types.src
	$(FLX) $(SRC)/stringm/cv_types.src
	$(FC2) cv_types.f90
	$(REMOVE_F) cv_types.f90

ftsm.o : $(SRC)/stringm/ftsm.src
	$(FLX) $(SRC)/stringm/ftsm.src
	$(FC2) ftsm.f90
	$(REMOVE_F) ftsm.f90

ftsm_rex.o : $(SRC)/stringm/ftsm_rex.src
	$(FLX) $(SRC)/stringm/ftsm_rex.src
	$(FC2) ftsm_rex.f90
	$(REMOVE_F) ftsm_rex.f90

ftsm_var.o : $(SRC)/stringm/ftsm_var.src
	$(FLX) $(SRC)/stringm/ftsm_var.src
	$(FC2) ftsm_var.f90
	$(REMOVE_F) ftsm_var.f90

ivector.o : $(SRC)/stringm/ivector.src
	$(FLX) $(SRC)/stringm/ivector.src
	$(FC2) ivector.f90
	$(REMOVE_F) ivector.f90

ivector_list.o : $(SRC)/stringm/ivector_list.src
	$(FLX) $(SRC)/stringm/ivector_list.src
	$(FC2) ivector_list.f90
	$(REMOVE_F) ivector_list.f90

parser.o : $(SRC)/stringm/parser.src
	$(FLX) $(SRC)/stringm/parser.src
	$(FC2) parser.f90
	$(REMOVE_F) parser.f90

sm0k.o : $(SRC)/stringm/sm0k.src
	$(FLX) $(SRC)/stringm/sm0k.src
	$(FC2) sm0k.f90
	$(REMOVE_F) sm0k.f90

sm_config.o : $(SRC)/stringm/sm_config.src
	$(FLX) $(SRC)/stringm/sm_config.src
	$(FC2) sm_config.f90
	$(REMOVE_F) sm_config.f90

sm_main.o : $(SRC)/stringm/sm_main.src
	$(FLX) $(SRC)/stringm/sm_main.src
	$(FC2) sm_main.f90
	$(REMOVE_F) sm_main.f90

sm_util.o : $(SRC)/stringm/sm_util.src
	$(FLX) $(SRC)/stringm/sm_util.src
	$(FC2) sm_util.f90
	$(REMOVE_F) sm_util.f90

smcv.o : $(SRC)/stringm/smcv.src
	$(FLX) $(SRC)/stringm/smcv.src
	$(FC2) smcv.f90
	$(REMOVE_F) smcv.f90

smcv_add.o : $(SRC)/stringm/smcv_add.src
	$(FLX) $(SRC)/stringm/smcv_add.src
	$(FC2) smcv_add.f90
	$(REMOVE_F) smcv_add.f90

smcv_master.o : $(SRC)/stringm/smcv_master.src
	$(FLX) $(SRC)/stringm/smcv_master.src
	$(FC2) smcv_master.f90
	$(REMOVE_F) smcv_master.f90

smcv_var.o : $(SRC)/stringm/smcv_var.src
	$(FLX) $(SRC)/stringm/smcv_var.src
	$(FC2) smcv_var.f90
	$(REMOVE_F) smcv_var.f90

splines.o : $(SRC)/stringm/splines.src
	$(FLX) $(SRC)/stringm/splines.src
	$(FC2) splines.f90
	$(REMOVE_F) splines.f90


# stringm dependency file

cv_angle_com.o : chutil.o consta_ltm.o cv_base.o cv_types.o ivector.o multicom_ltm.o parallel_ltm.o stream_ltm.o \
    string.o

cv_anglvec.o : chutil.o consta_ltm.o cv_base.o cv_frames.o cv_types.o ivector_list.o multicom_ltm.o parallel_ltm.o \
    stream_ltm.o string.o

cv_base.o : consta_ltm.o cv_types.o ivector_list.o lu.o multicom_ltm.o multidiag.o number_ltm.o parallel_ltm.o \
    sm_config.o smcv_var.o string.o

cv_cvrms.o : consta_ltm.o cv_angle_com.o cv_anglvec.o cv_base.o cv_dihe_com.o cv_dist_com.o cv_drmsd.o cv_posi_com.o \
    cv_proj.o cv_qcomp.o cv_rmsd.o cv_types.o ivector.o multicom_ltm.o parallel_ltm.o stream_ltm.o \
    string.o

cv_dihe_com.o : chutil.o consta_ltm.o cv_base.o cv_types.o ivector.o multicom_ltm.o parallel_ltm.o stream_ltm.o \
    string.o

cv_dist_com.o : chutil.o cv_base.o cv_types.o ivector.o multicom_ltm.o parallel_ltm.o stream_ltm.o string.o

cv_drmsd.o : bestfit.o chutil.o consta_ltm.o cv_base.o cv_types.o ivector.o multicom_ltm.o parallel_ltm.o \
    stream_ltm.o

cv_frames.o : bestfit.o chutil.o cv_base.o ivector_list.o multicom_ltm.o number_ltm.o parallel_ltm.o smcv_var.o \
    stream_ltm.o string.o

cv_posi_com.o : chutil.o cv_base.o cv_frames.o cv_types.o multicom_ltm.o parallel_ltm.o stream_ltm.o string.o

cv_proj.o : bestfit.o consta_ltm.o cv_base.o cv_drmsd.o

cv_qcomp.o : cv_base.o cv_quaternion.o cv_types.o multicom_ltm.o parallel_ltm.o stream_ltm.o string.o

cv_quaternion.o : cv_base.o cv_frames.o ivector.o multicom_ltm.o number_ltm.o parallel_ltm.o stream_ltm.o string.o

cv_rmsd.o : bestfit.o chutil.o consta_ltm.o cv_base.o cv_types.o ivector.o multicom_ltm.o parallel_ltm.o \
    stream_ltm.o

ftsm.o : bestfit.o chutil.o random.o consta_ltm.o coord_ltm.o coordc_ltm.o coorio.o ctitla_ltm.o \
    cveloci.o cvio.o dimens_ltm.o exfunc_ltm.o ftsm_rex.o ftsm_var.o ivector.o multicom.o \
    multicom_ltm.o number_ltm.o parallel_ltm.o psf_ltm.o reawri_ltm.o selcta.o sm_config.o stream_ltm.o \
    string.o

ftsm_rex.o : consta_ltm.o ftsm_var.o ivector.o multicom_ltm.o parallel_ltm.o string.o

ftsm_var.o : sm_config.o smcv_var.o

ivector.o : string.o

ivector_list.o : ivector.o string.o

parser.o : exfunc_ltm.o ivector.o string.o

sm0k.o : bestfit.o coord_ltm.o coordc_ltm.o coorio.o corsubs.o ctitla_ltm.o dimens_ltm.o energy_ltm.o \
    eutil.o exfunc_ltm.o multicom_ltm.o number_ltm.o parallel_ltm.o psf_ltm.o selcta.o sm_config.o \
    stream_ltm.o string.o tsmh_ltm.o tsms.o

sm_main.o : consta_ltm.o dimens_ltm.o exfunc_ltm.o ftsm.o ftsm_var.o machio.o multicom_ltm.o number_ltm.o \
    parallel_ltm.o sm0k.o smcv_var.o stream_ltm.o string.o

sm_util.o : cv_base.o cv_frames.o dimens_ltm.o multicom_ltm.o multidiag.o parallel_ltm.o smcv_master.o smcv_var.o \
    stream_ltm.o string.o

smcv.o : consta_ltm.o coord_ltm.o coordc_ltm.o coorio.o ctitla_ltm.o cv_base.o cv_frames.o cv_quaternion.o \
    dimens_ltm.o exfunc_ltm.o multicom_ltm.o number_ltm.o parallel_ltm.o psf_ltm.o sm_config.o smcv_master.o \
    smcv_var.o stream_ltm.o string.o

smcv_add.o : coord_ltm.o coordc_ltm.o cv_angle_com.o cv_anglvec.o cv_base.o cv_cvrms.o cv_dihe_com.o cv_dist_com.o \
    cv_drmsd.o cv_frames.o cv_posi_com.o cv_proj.o cv_qcomp.o cv_quaternion.o cv_rmsd.o cv_types.o \
    dimens_ltm.o exfunc_ltm.o ivector.o multicom_ltm.o number_ltm.o parallel_ltm.o parser.o psf_ltm.o \
    selcta.o sm_config.o stream_ltm.o string.o

smcv_master.o : random.o consta_ltm.o cv_angle_com.o cv_anglvec.o cv_base.o cv_cvrms.o cv_dihe_com.o cv_dist_com.o \
    cv_drmsd.o cv_frames.o cv_posi_com.o cv_proj.o cv_qcomp.o cv_quaternion.o cv_rmsd.o cv_types.o \
    exfunc_ltm.o lu.o multicom.o multicom_ltm.o parallel_ltm.o reawri_ltm.o sm_config.o smcv_var.o \
    stream_ltm.o string.o

splines.o : string.o
