#!/bin/bash
# run multiple chest calcs with different parameters
source ~/scripts/struna.sh
template=template.dat


 gbuf=6 ;
 dgrid=1 ;
 qsig=1
 epssig=1;
 epsin=1;
 epsout=78;
 config="run.dat"
 epspad=0.3 ;

 for dgrid in 1 0.8 0.6 0.5 0.4 0.3 0.2 ; do
  echo
  echo "Grid size : $dgrid"
  echo "------------------"
#  qsig=`echo "0.2 * $dgrid" | bc -l`;
#  epssig=`echo "0.2 * $dgrid" | bc -l`;

# calc in water
  epsout=78
  cp $template $config
  for key in dgrid gbuf qsig epssig epspad epsin epsout ; do
    update $config $key
  done
  esol=`./ches 2>&1 $config | grep "grid energy" |awk '{print $NF}'`
  echo E_solute : $esol

# repeat in vacuum
  epsout=1
  cp $template $config
  for key in dgrid gbuf qsig epssig epspad epsin epsout ; do
    update $config $key
  done
  evac=`./ches 2>&1 $config | grep "grid energy" |awk '{print $NF}'`
  echo E_vacuum : $evac
  de=`echo "$esol - ($evac)" | bc -l`
  echo "-------------------"
  echo dE: $de
 done
