#!/bin/bash
# run multiple chest calcs with different parameters
source ~/scripts/struna.sh
#template=template.dat
template=template-np.dat


 gbuf=6 ;
 dgrid=1 ;
 np=66 ;
 qsig=1.047
 epssig=1.;
 epsin=1;
 epsout=78;
 config="run.dat"
 epspad=-0.6 ;

# for dgrid in 1 0.8 0.6 0.5 0.4 0.3 0.2 ; do
 for np in 32 48 64 96 128 192 256 320 384 ; do
# for np in 32 48 64 96 128 192 ; do
  nx=$((np+2))
  ny=$((np+2))
  nz=$((np+2))
  echo
#  echo "Grid resolution : $dgrid"
  dgrid=`echo "(29 - (-29) )/${np}" | bc -l`
  echo "Grid size : ${np}^3"
  echo "Grid resolution : $dgrid"
  echo "------------------"
#  qsig=`echo "0.2 * $dgrid" | bc -l`;
#  epssig=`echo "0.2 * $dgrid" | bc -l`;

# calc in water
  epsout=78
  cp $template $config
  for key in dgrid gbuf qsig epssig epspad epsin epsout nx ny nz; do
    update $config $key
  done
  esol=`./ches 2>&1 $config | grep "grid energy" |awk '{print $NF}'`
  esollr=`./ches 2>&1 $config | grep "Long-range" |awk '{print $NF}'`
  echo "E_solvent : $esol, $esollr"

# repeat in vacuum
  epsout=${epsin}
  cp $template $config
  for key in dgrid gbuf qsig epssig epspad epsin epsout nx ny nz ; do
    update $config $key
  done
  evac=`./ches 2>&1 $config | grep "grid energy" |awk '{print $NF}'`
  evaclr=`./ches 2>&1 $config | grep "Long-range" |awk '{print $NF}'`
  echo "E_vacuum : $evac, $evaclr"
  de=`echo "$esol - ($evac)" | bc -l`
  delr=`echo "$esollr - ($evaclr)" | bc -l`
  echo "-------------------"
  echo "dE: $de, $delr"
 done
