#!/bin/bash

mkdir -p data

irep=0
brep=0
erep=15

vmd -dispdev text < alist.vmd >/dev/null #generate ftsm atom indices

for irep in `seq $brep $erep`; do
# prepare input file from template
#
  config=${irep}.in
  output=${irep}.out
  pluginfile=diala.fts${irep}
  pluginout=${pluginfile}.out

  if [ $brep -eq $irep ] ; then
   dpar=0
  elif [ $erep -eq $irep ] ; then
   dpar=1
  else
   dpar=0.5
  fi

  cat template.sm | \
  sed "s/@{orientation}/atomid `cat orient.dat`/g" | \
  sed "s/@{forcing}/atomid `cat forced.dat`/g" | \
  sed "s/@{dpar}/$dpar/g" | \
  sed "s/@{irep}/$irep/g" | \
  cat > $pluginfile

  cat template |\
   sed "s/@{coordinates}/data\/diala22_zts_$irep.pdb/g" | \
   sed "s/@{input}/$pluginfile/g" | \
   sed "s/@{log}/$pluginout/g" | \
   cat > $config

  acemd $config #> $output
exit
done
