#!/bin/bash

flag=""

jname=zts

charmm=../../../../exec/gnu_M/charmm
charmm=charmm_repo

mpirun="mpirun --bind-to none"

echo localhost > nodes

mkdir -p data

count=1

nodes=4 # total number of cores
nodes=8
nodes=16

mkdir -p data
script=diala22_zts.inp

$mpirun -n $nodes -machinefile nodes $charmm a=$script nrun=$count restart=0 -i $script -o out_$nodes

