#!/bin/bash

flag=""

jname=zts

# charmm executable :
charmm=charmm_repo

mpirun="mpirun --bind-to none"


mkdir -p data

count=1

nodes=4 # total number of cores
nodes=8
#nodes=16

echo "localhost slots=$nodes" > nodes

mkdir -p data
script=diala22_zts.inp

$mpirun -n $nodes -machinefile nodes $charmm a=$script nrun=$count restart=0 -i $script -o out_$nodes

