#!/bin/bash
# run all steps in the test
charmm=charmm-omm
python=python

$charmm -i gene.inp -o gene.out # generate structure and initial coordinate file
# equilibrate
$python < equil.py > equil.out
# run string code window-per-window
echo "3 14 15 92" > rng_seeds0.dat
$python < md.py > md.out



