ROOT=../..
OBJS=angles.o bonds.o dihedrals.o
HEADS=interface.h
NAME=dynamol/compute
DEPS=constants dynamol/struc dynamol/param
include $(ROOT)/Makefile.inc

#$(ROOT)/$(NAME).stamp :: interface.h
#	file=$< ; ln -fs `pwd`/$$file ${ROOT}/include/$$file;
#	echo -n > $@

#clean::
#	rm -f interface.h

#.SILENT : $(ROOT)/$(NAME).stamp
