#!/bin/bash 
#2D umbrella sampling using string method in CHARMM
#
# execution parameters
charmm=charmm_repo
mpirun=/usr/lib/openmpi/bin/mpirun
echo localhost > ~/nodes

cores=7

charmrun=./charmrun
namd=./namd2.10

#namd=namd2.12


# simulation parameters
pi=3.1415926535 ;
phis=-180
psis=-180
phie=`echo "$phis+360.0" |bc -l`
psie=`echo "$psis+360.0" |bc -l`

fbw=5 # degrees;
fbwrad=`echo "$fbw/180*$pi" |bc -l` # flat bottom region in radians

nphi=40
npsi=40


for iphi in `seq 1 $nphi`; do
 for jpsi in `seq 1 $npsi`; do
# to rerun windows manually, set the indices below and exit before end of loop
#iphi=34
#jpsi=36

  myphi=`echo "scale=2; $phis + ( $phie - $phis ) * ( $iphi - 1 ) / ( $nphi ) " |bc -l` ; # not going up to phie in view of periodicity
  mypsi=`echo "scale=2; $psis + ( $psie - $psis ) * ( $jpsi - 1 ) / ( $npsi ) " |bc -l` ;

  phirad=`echo "$myphi/180*$pi" | bc -l` 
  psirad=`echo "$mypsi/180*$pi" | bc -l` 

# RUN SIMULATION
####################
  echo "Running window ($iphi,$jpsi) ~ ($myphi, $mypsi) ..."
#
# prepare input file from template
#
  flag=${iphi}_${jpsi}
#
  cat template.sm | \
  sed "s/@phirad/$phirad/g" | \
  sed "s/@psirad/$psirad/g" | \
  sed "s/@phi/$myphi/g" | \
  sed "s/@psi/$mypsi/g" | \
  sed "s/@fbw/$fbwrad/g" |\
  cat > ${flag}.us2d.smcv


  cat template |\
   sed "s/@smcvconfig/${flag}.us2d.smcv/g" |\
   sed "s/@smcvlog/${flag}.us2d.smcv.log/g" |\
   sed "s/@outputname/${flag}/g" |\
   cat > ${flag}.in

  irun=$((irun+1))
  if [ "$irun" -eq "$cores" ]; then
   irun=0
#   $charmrun +p1 
   $namd ${flag}.in > ${flag}.out
  else
#   $charmrun +p1 
   $namd ${flag}.in > ${flag}.out &
  fi

exit

 done
done

