ROOT=../..
OBJS = mol_formats.o charmmio.o freeio.o pdbio.o corio.o
NAME=dynamol/coor
DEPS=parser output dynamol/struc

include $(ROOT)/Makefile.inc
corio.o : mol_formats.o charmmio.o freeio.o pdbio.o
