ROOT=../..
COMMON=..
OBJS=plot3dio.o util.o formats.o chestio.o fieldio.o
NAME=continua/io
DEPS=parser output files

include $(ROOT)/Makefile.inc
include $(COMMON)/Makefile.inc

#libs : libio.a
fieldio.o : plot3dio.o util.o formats.o chestio.o

