#!/bin/bash

lib=~/scripts/
clib=$lib/charmm

name=alad
charmm=c45b1str
python=python

if [ 0 -eq 1 ]; then
# solvate in a cubic box if needed
ln -s ../$name.psf
ln -s ../${name}_m.cor
$charmm -i $clib/boxsolv.inp psffile=$name corfile=${name}_m buf=15 method=cube -o solvate.out

# equilibrate
python < equil.py >& equil.out

fi

# run string simulations
nohup ./driver
