LINKOBJS=\
 erfappx.o \
 erfsun_ref.o \
 erfsun_value.o \
 constants.o\
 output.o \
 parser.o \
 parselist.o \
 cmd.o prm.o \
 files.o \
 mpi_compat_stub.o \
 ivector.o \
 isort.o \
 state.o \
 fieldbcdef.o \
 system.o \
 stats.o \
 rng.o \
 clcg.o \
 psf.o \
 psfatom.o \
 tlist.o \
 charmmio.o \
 pdbio.o \
 corio.o \
 freeio.o \
 formats.o \
 chestio.o \
 plot3dio.o \
 util.o \
 mol_formats.o \
 ch_param.o \
 anglpar.o \
 bondpar.o \
 dihepar.o \
 atompar.o \
 bonds.o \
 angles.o \
 dihedrals.o
 