#!/bin/bash

minwat=9999999999
minsod=9999999999
mincla=9999999999

for f in `ls temp/*n.psf`; do
 natom=`grep "!NATOM" $f | awk '{ print $1}'`
 nwat=`grep ' O\?WAT ' $f | wc -l` ; nwat=`echo $nwat / 3 | bc ` 
 nsod=`grep "ION1" $f | awk '{ print $3}' | tail -n1`
 ncla=`grep "ION2" $f | awk '{ print $3}' | tail -n1`

echo $f $nwat

 minwat=$(( minwat > nwat ? nwat : minwat))
 minsod=$(( minsod > nsod ? nsod : minsod))
 mincla=$(( mincla > ncla ? ncla : mincla))

done

echo " Minimum number of water molecules : $minwat"
echo " Minimum number of Na+ ions        : $minsod"
echo " Minimum number of Cl- ions        : $mincla"
