#!/bin/bash 
#2D umbrella sampling using string method in CHARMM
#
# execution parameters
charmm=charmm_repo
mpirun=/usr/lib/openmpi/bin/mpirun
echo localhost > ~/nodes
nodes=1

# simulation parameters

phis=-180
psis=-180
phie=`echo "$phis+360.0" |bc -l`
psie=`echo "$psis+360.0" |bc -l`

nphi=20
npsi=20


for iphi in `seq 1 $nphi`; do
 for jpsi in `seq 1 $npsi`; do

  myphi=`echo "scale=2; $phis + ( $phie - $phis ) * ( $iphi - 1 ) / ( $nphi ) " |bc -l` ; # not going up to phie in view of periodicity
  mypsi=`echo "scale=2; $psis + ( $psie - $psis ) * ( $jpsi - 1 ) / ( $npsi ) " |bc -l` ;

# RUN SIMULATION
####################
  echo "Running window ($iphi,$jpsi) ~ ($myphi, $mypsi) ..."

  flag=${iphi}_${jpsi}

  script=us2d.inp

  $mpirun -n $nodes -machinefile ~/nodes $charmm -i $script myphi=$myphi mypsi=$mypsi -o ${flag}.out

 done
done

