#!/bin/bash
# wrapper to prepare psf coordinates and parameters for acemd run of rab
charmm=charmm
#toppar="/home/surgeon/charmm/parameters/c36"
# make parameter file
#./mergepar ${toppar}/par_all36_prot.prm ${toppar}/par_all36_na.prm ${toppar}/stream/toppar_all36_na_nad_ppi.str ${toppar}/toppar_water_ions.str 
# make list of ftsm atom indices
#vmd -dispdev text < alist.vmd
# subsample string to 32 replicas (from 64)
#vmd -dispdev text < newstring.vmd
#exit
# make coordinates and psf
#mkdir -p scratch
mpirun -np 32 $charmm -i mkstring.inp #-o mkstring.out
