#!/bin/bash

n=100000 ;

echo "
import random;
rand=[random.random() for i in range($n)] ; 
fout=open('random.dat','w') ; 
for r in rand: print >> fout, r"  | python2

echo " d=load('random.dat'); hist(d) ;pause (-1)" | octave
rm -f random.dat
