#!/bin/bash

if [ -z $1 ] ; then
 echo "USAGE ./mpi <executable> <input>"
 exit 1
fi

if [ -z $2 ] ; then
 echo "USAGE ./mpi <executable> <input>"
 exit 1
fi

echo localhost > nodes

/usr/bin/mpirun -machinefile nodes -np 5 $1 $2
