#!/bin/bash

if [ -z $1 ] ; then
 echo "USAGE ./mpi <executable> <input>"
 exit 1
fi

if [ -z $2 ] ; then
 echo "USAGE ./mpi <executable> <input>"
 exit 1
fi

echo localhost > nodes
np=1
mpirun=/usr/bin/mpirun 
mpirun=mpirun

$mpirun -machinefile nodes -np $np $1 $2
