#!/bin/bash 
echo localhost > ~/nodes
nodes=1

# simulation parameters

d0=12 ;
d1=32 ;

fbw=1

nwin=32 ;


for i in `seq 1 $nwin`; do

  d=`echo "scale=2 ; $d0 + ( $d1 - $d0 ) * ( $i - 1 ) / ( $nwin - 1 ) " |bc -l`

# RUN SIMULATION
####################
  echo "Running window (d = $d) ..."
#
# prepare input file from template
#
  cat template.smcv | \
  sed "s/@fbw/$fbw/g" | \
  sed "s/@dref/$d/g" | \
  sed "s/@fbw/$fbwrad/g" > deca.smcv

  flag=${d}

  cat template.py |\
   sed "s/@nrun/$i/g" |\
   sed "s/@nprev/$((i-1))/g" |\
   sed "s/@smconfig/'deca.smcv'/g" |\
   sed "s/@smlog/'deca.smcv.log'/g" |\
   cat > deca.py
#exit
  time python deca.py > deca${flag}.out
#exit
done

