ROOT=..
OBJS=ppoly1.o ppoly2.o bracket.o
NAME=ppoly

LINKOBJS=output.o files.o parser.o ivector.o prm.o cmd.o isort.o constants.o
TESTOBJS=$(OBJS)

LOCALMACROS+=-include bracket.def

include $(ROOT)/Makefile.inc

