#!/bin/bash
# run all steps in the test
charmm=c45b1str
python=python

#$charmm -i gene.inp -o gene.out # generate structure and initial coordinate file
# equilibrate
#python < equil.py > equil.out
# run string code window-per-window
./driver
