#!/bin/sh

log=update_log
echo -n > $log

for file in `ls *.src`; do
 sed -e 's/integer/int/g' \
     -e 's/real\*8/float/g' \
     -e 's/int\*4/mpiint/g' \
     -e 's/logical/bool/g' \
     -e 's/character\*/character(len=/g' \
     -e 's/##/__CHARMM_ONLY##/g' \
     -e 's/use mpi/__DEP_MPI/g'\
     -e 's/use multicom/__DEP_MULTICOM/g'\
     -e 's/cv_base/cv_common/g'\
     -e 's/implicit none/__IMPNONE/g'\
 < $file > temp.f
 if [ -f temp.f ]; then 
  diff $file temp.f --side-by-side --suppress-common-lines >> $log
  mv -f temp.f ${file%%.*}.ftn
 fi
 
done

