#!/bin/bash
topfile="struc/sosip36.top"
prmfile="struc/sosip36.par"
psffile="struc/g120-ab-trunc_sn.psf"
pdbfile="struc/g120-ab-trunc-ressn.pdb"
corfile="struc/g120-ab-trunc-ressn.cor"
name="g120-ab-trunc"
