#!/bin/bash
#
omm_version="8.0.0rc1" ;# what to compile against, and where to put the libs
omm_version="7.3.0" ;# what to compile against, and where to put the libs

OMMDIR=/usr/local/openmm-git-${omm_version}
DYNAMODIR=/home/surgeon/projects
PYTHON=`which python`

rm -fr build-${omm_version}
mkdir -p build-${omm_version}
pushd build-${omm_version}

#cmake ../ -DCMAKE_CXX_COMPILER=/usr/bin/c++ -DCMAKE_C_COMPILER=/usr/bin/cc -DOPENMM_DIR=$OMMDIR -DCMAKE_INSTALL_PREFIX=$OMMDIR -DDYNAMO_INCLUDE_DIR=$DYNAMODIR/include \
# -DDYNAMO_LIBRARY_DIR=$DYNAMODIR/lib -DPYTHON_EXECUTABLE=$PYTHON -DDYNAMO_BUILD_OPENCL_LIB=ON -DDYNAMO_SINGLE_PRECISION=OFF
cmake ../ -DCMAKE_CXX_COMPILER=/usr/bin/c++-8 -DCMAKE_C_COMPILER=/usr/bin/cc-8 -DOPENMM_DIR=$OMMDIR -DCMAKE_INSTALL_PREFIX=$OMMDIR -DDYNAMO_INCLUDE_DIR=$DYNAMODIR/include \
 -DDYNAMO_LIBRARY_DIR=$DYNAMODIR/lib -DPYTHON_EXECUTABLE=$PYTHON -DDYNAMO_BUILD_OPENCL_LIB=ON -DDYNAMO_SINGLE_PRECISION=OFF -DCUDA_NVCC_FLAGS='-gencode arch=compute_75,code=sm_75'
# run again
#cmake ../ -DOPENMM_DIR=$ROOT -DCMAKE_INSTALL_PREFIX=$ROOT -DDYNAMO_INCLUDE_DIR=$ROOT/victor/include \
# -DDYNAMO_LIBRARY_DIR=$ROOT/victor/lib -DPYTHON_EXECUTABLE=$PYTHON
make -j12
sudo make install
sudo make PythonInstall
popd

