#!/bin/bash
#

OMPDIR=/usr/local/openmm-git
DYNAMODIR=~/projects
PYTHON=`which python`

rm -fr build
mkdir -p build
pushd build
cmake ../ -DCMAKE_CXX_COMPILER=/usr/bin/c++-8 -DCMAKE_C_COMPILER=/usr/bin/cc-8 -DOPENMM_DIR=$OMPDIR -DCMAKE_INSTALL_PREFIX=$OMPDIR -DDYNAMO_INCLUDE_DIR=$DYNAMODIR/include \
 -DDYNAMO_LIBRARY_DIR=$DYNAMODIR/lib -DPYTHON_EXECUTABLE=$PYTHON
# run again
#cmake ../ -DOPENMM_DIR=$ROOT -DCMAKE_INSTALL_PREFIX=$ROOT -DDYNAMO_INCLUDE_DIR=$ROOT/victor/include \
# -DDYNAMO_LIBRARY_DIR=$ROOT/victor/lib -DPYTHON_EXECUTABLE=$PYTHON
make -j8
sudo make install
sudo make PythonInstall
popd

