#!/bin/bash
#
omm_version="8.0.0rc1" ;# what to compile against, and where to put the libs
omm_version="7.3.0" ;# what to compile against, and where to put the libs
gnuver="-8"

OMMDIR=/usr/local/openmm-git-${omm_version}
#OMMDIR=/usr/local/openmm-git
DYNAMODIR=/home/surgeon/projects
PYTHON=`which python`

rm -fr build-${omm_version}
mkdir -p build-${omm_version}
pushd build-${omm_version}

cmake ../ -DCMAKE_CXX_COMPILER=/usr/bin/c++${gnuver} -DCMAKE_C_COMPILER=/usr/bin/cc${gnuver} -DOPENMM_DIR=$OMMDIR -DCMAKE_INSTALL_PREFIX=$OMMDIR -DDYNAMO_INCLUDE_DIR=$DYNAMODIR/include \
 -DDYNAMO_LIBRARY_DIR=$DYNAMODIR/lib -DPYTHON_EXECUTABLE=$PYTHON -DDYNAMO_BUILD_OPENCL_LIB=ON -DOPENCL_INCLUDE_DIR=/opt/cuda/include -DDYNAMO_SINGLE_PRECISION=OFF

make -j12
sudo make install
sudo make PythonInstall
popd

