#!/bin/bash

if [ -z $1 ] ; then 
 files=`ls npt[0-9]* | sed 's/.*crash//'`;
 farr=($files)
 last=${#farr[@]}
 f=${farr[$last - 1 ]}
 echo "Reading from file $f ..."
else
 f=$1
fi
#
if [ -z $2 ] ; then 
 term=total
else
 term=$2
fi
#
tail -n +5 $f | grep -ve "^[TCL|#]" > _temp
#grep -ve "^[TCL|#]" $f > _temp

#     Step      Bond     Angle     Dihed      Elec       VDW        PE        KE  Externa     Total      Temp      Pres   PresAve

echo "d=load(\"_temp\"); \
 step=1;
 bond=2;
 angl=3;
 dihe=4;
 elec=5;
 vdw=6;
 pe=7;
 ke=8;
 exte=9;
 total=10;
 temp=11;
 pres=12;
 prav=13;
 plot(d(:,step), d(:,$term));
 mean(d(:,$term))
 pause(10) " > _plote;
#
 if [ ! -z $3 ] && [ ! -z $4 ]; then
  echo "ylim([$3 $4])" >> _plote;
 fi
#
 echo "pause(0)" >> _plote;

octave < _plote;
