% compute free energy from histogram generated by TAMD
%
close all;

cvhist=load('deca_tamd_cv.dat');

temp=4000;
kb=1.98719e-3;

x0=13 ;
x1=31 ;
dx=1  ;

x=x0:dx:x1 ;

[nn,x]=hist(cvhist,x) ;

fe = - kb * temp * log(nn); fe=fe-min(fe) ;

plot(x,fe,'k.-')
%pause(1000)

