#!/bin/bash
file=$1
flag=`grep -i "automatically protect all code" $file`;\
if [ -z "$flag" ];then\
 line_module_begin=`grep -niE "^\s*module\s+" $file`;\
 if [ -z "$line_module_begin" ]; then \
  lbeg=1;\
  lend=`wc -l $file |awk {'print $1'}`;\
  lend=$((lend+1))
 else \
  lbeg=${line_module_begin%%:*};\
  line_module_end=`grep -niE "^\s*end\s+module\s+" $file`;\
  lend=${line_module_end%%:*};\
 fi;\
 sed --follow-symlinks -i "${lbeg}a ##IF STRINGM ! automatically protect all code within module scope" $file;\
 sed --follow-symlinks -i "${lend}a ##ENDIF ! automatically protect all code inside module scope" $file;\
fi;
