#!/bin/bash
# simpler alternative to matlab code

base=force
brep=0
erep=7
#brun=0
#erun=49

freps=""

# first join multiple runs together for each force file :

for irep in `seq ${brep} ${erep}` ; do
 frep=${base}${irep}.dat
# echo -n > $frep 
 freps="$freps $frep" # save filenames for second step
# for irun in `seq ${brun} ${erun}` ; do
#  cat ${base}${irun}_${irep}.dat >> $frep
# done
done

# now combine replica files
paste $freps > ${base}.dat
