#!/bin/bash
# Check for a fortran compiler
if [ -z "$1" ]; then
 echo "No Fortran Compiler Specified"
 for comp in g77 gfortran ifort f77 f90 pathf77 pathf90 pgff77 pgf90 pgf95 ifc; do
  echo "Checking for '${comp}': "
  echo -n "${comp} -v 2>&1 | grep -i version ==> "
  version=`${comp} -v 2>&1 | grep -i version`
  echo -n $version" ... "
  if [ ! -z "$version" ]; then
   echo "ok"; FC=${comp}; FFLAGS="-O1"; DEFS="-D float=real*8";
   break
  else
   echo "no"
  fi
 done
else
 FC="$1"
 if [ -z "$2" ]; then
  FFLAGS="-O1"
  DEFS="-D float=real*8"
 else
  FFLAGS=`echo "$2" | sed s/\-c//` ;# remove "-c" flag, since we want to produce an executable, not an object file
  if [ -z "$3" ]; then
   DEFS="-D float=real*8"
  else
   DEFS="$3"
  fi
 fi
fi
