#!/bin/bash
# 3D test case for chest
# V. Ovchinnikov 2019
# Numerical solution to the poisson equation in three dimensions (known analytical solution)
#
# Requires a fortran compiler
. ./fcheck "$1" "$2" "$3" ;# execute script in the current context
# electrostatic potential due to a single Gaussian charge, i.e.
# rho=-Q/(sqrt(2*pi)*s)**3 * exp(-0.5d0*(dr/s)**2)
# the potential is represented analytically only if the permittivity is uniform
# in which case the solution is expressed via the error function :
# U = Q / (4*pi*eps) * erf( r / (sqrt(2) * s )) / r
# where Q is the charge, eps is the permittivity, s is the std of the Gaussian
# and r is the distance to the charge.
# Otherwise, analytical solution can be computed as a 1D numerical integral
# This test case is different from test3d-11 in terms of how the source is specified:
# here the molecule context is used, which prepares a single gaussian-filtered ball
#
# parameters :
# grid size
nx=34; ny=34; nz=34;
nx=50; ny=50; nz=50;
nx=66; ny=66; nz=66;
nx=98; ny=98; nz=98;
nx=130; ny=130; nz=130;
#nx=258; ny=258; nz=258;
#nx=386; ny=386; nz=386;
#
omega=1.44 # SOR acceleration
ccelec=332.0716;
pi=3.141592653589793;
eps0=`echo "1.0 / (${ccelec} * 4.0 * $pi )" | bc -l` ; # charmm electrostatics constant
#eps0=1
ein=1 ;# scaled permittivity inside
eout=1 ;# scaled permittivity outside
s=0.4;
Q=1;
R=1.316 ;# nominal radius of born cavity
pad=1.168;# cavity padding
useBornBC=0 ;# test using Born/DH BCs, rather than exact ; Born should be acceptable in this case (generally, as long as the boundary is far from charge)
useObjectBC=1;# test using Born/DH BCs computed from the pqr file by the code, rather than specified here in precomputed arrays
blen=6;# box side half-length
qbin=1;# binary I/O for speed
if [ $qbin -eq 1 ] ; then
 IOMODE="binary"
# find out precision with which code was compiled
 echo "
 init=none
 exec=info
 info{
  exec:precision
 }" > test.dat
#
 if [ -z "`./ches test.dat 2>&1 | grep -i double`" ]; then
  qdouble=0
  echo "SINGLE PRECISION COMPILATION DETECTED"
 else
  qdouble=1
  echo "DOUBLE PRECISION COMPILATION DETECTED"
 fi
#
 if [ $qdouble -eq 0 ] ; then
  DEFS+=" -Ufloat -Dfloat=real*4 " # only single precision output in binary
 fi
else
 IOMODE="text"
fi
#
echo
echo " *********************************************************************************************"
echo " (test3d-11i) "
echo " Test case for solving 3D Poisson equation using CHES"
echo " Laplacian U  = f"
echo " Dirichlet boundary conditions assigned on the boundary"
#echo " Jacobi smoother with step (omega) = $omega " ;# varies
echo " *********************************************************************************************"
#

xstretch=1.0; x0=-$blen; x1=$blen
ystretch=1.0; y0=-$blen; y1=$blen
zstretch=1.0; z0=-$blen; z1=$blen
#
#
echo " Generating test data..."
echo "
  implicit none
  float :: x1($nx), y1($ny), z1($nz)
  float :: x2($nx), y2($ny), z2($nz)
  float :: xbc0($ny,$nz), xbc1($ny,$nz)
  float :: ybc0($nx,$nz), ybc1($nx,$nz)
  float :: zbc0($nx,$ny), zbc1($nx,$ny)
  float :: rhs($nx,$ny,$nz), u($nx,$ny,$nz), eps($nx, $ny, $nz)
  float, parameter :: err = 1d-12, sq2=sqrt(2d0)
  float :: a, b, l, z, pi, delta, xcen, ycen, zcen, drn
  integer :: i, j, k, n
! variables for analytical solution
  integer, parameter :: npt = 500000
  float, parameter :: rmin=0d0
  float :: rmax
  float :: dr
  float :: r(npt), phi(npt), rhoint(npt)
  float, parameter :: rpad=${R}d0+${pad}d0, s=${s}d0
!
  if (${useBornBC}.eq.1) then
   rmax = max ( ${R}d0 + ${pad}d0 + 5d0*${s}d0 , 1d0 + 0.5d0 * sqrt( ((${x1}d0)-(${x0}d0))**2 + ((${y1}d0)-(${y0}d0))**2 + ((${z1}d0)-(${z0}d0))**2 ) )
  else
   rmax=${R}d0 + ${pad}d0 + 5d0*${s}/${eps0}d0 ! need to go out far if phi(rmax) ~= 0 ! Otherwise, would need to use another BC, e.g. Born/DH
  endif
  dr=(rmax-rmin)/(npt-1)
! write(0,*) rmax

  pi=atan(1d0)*4d0
! construct analytical solution numerically
! charge density integral :
  rhoint(1)=0d0
  r(1)=rmin
  do i=2, npt
   r(i)=r(i-1)+dr
   drn=r(i)/${s}d0
   delta=${eps0}d0*(${eout} + (${ein}-${eout})*ball(r(i),rpad,s))
   if (r(i).lt.1d-3) then
    rhoint(i)=${Q}d0 * r(i)/( 3d0 * (s*sqrt(2d0*pi))**3 ) ! Taylor
   else
    rhoint(i)=${Q}d0 * ( erf(drn/sq2) / (4d0*pi) - (drn) * exp(-0.5d0*drn**2) / sqrt(2d0*pi)**3 )/r(i)**2/delta
   endif
  enddo
! integrate from infinity to 1 to obtain potential :
  if (${useBornBC}.eq.1) then
   phi(npt)=${Q}d0/(4d0*pi*r(npt)*${eps0}*${eout})
  else
   phi(npt)=0d0
  endif
  do i=npt-1, 1,-1
    phi(i)=phi(i+1) + 0.5d0 * (rhoint(i) + rhoint(i+1)) * (r(i+1)-r(i));
  enddo
! now, we can use phi as an approximation to the true solution
!
!
! xgrid:
  a=${x0}d0; b=${x1}d0; z=${xstretch}d0; n=$nx-1
  l=b-a
  if (ABS(z-1.0d0).lt.ERR) then
   delta=l/(n-1)
  else
   delta=l*(1.0d0-z)/(1.0d0-(z**(n-1)))
  endif
!
  x1(1)=a
  do i=2,n+1
   x1(i)=x1(i-1)+delta;
   delta=delta*z;
  enddo
!
  open(1,file='xg_test.dat',form='formatted', status='unknown')
  write(1,'(F30.15)') x1 
  close(1)
!
  x2(2:$nx)=0.5d0*(x1(1:$nx-1)+x1(2:$nx)); x2(1)=x1(1)-0.5d0*(x1(2)-x1(1)); 
!
! ygrid:
  a=${y0}d0; b=${y1}d0; z=${ystretch}d0; n=$ny-1
  l=b-a 
  if (ABS(z-1.0d0).lt.ERR) then
   delta=l/(n-1)
  else
   delta=l*(1.0d0-z)/(1.0d0-(z**(n-1)))
  endif
!
  y1(1)=a
  do i=2,n+1
   y1(i)=y1(i-1)+delta;
   delta=delta*z;
  enddo
!
  open(1,file='yg_test.dat',form='formatted', status='unknown')
  write(1,'(F30.15)') y1 
  close(1)
!
  y2(2:$ny)=0.5d0*(y1(1:$ny-1)+y1(2:$ny)); y2(1)=y1(1)-0.5d0*(y1(2)-y1(1));
!
! zgrid:
  a=${z0}d0; b=${z1}d0; z=${zstretch}d0; n=$nz-1
  l=b-a
  if (ABS(z-1.0d0).lt.ERR) then 
   delta=l/(n-1)
  else
   delta=l*(1.0d0-z)/(1.0d0-(z**(n-1)))
  endif
!
  z1(1)=a
  do i=2,n+1
   z1(i)=z1(i-1)+delta;
   delta=delta*z;
  enddo
!
  open(1,file='zg_test.dat',form='formatted', status='unknown')
  write(1,'(F30.15)') z1 
  close(1)
!
  z2(2:$nz)=0.5d0*(z1(1:$nz-1)+z1(2:$nz)); z2(1)=z1(1)-0.5d0*(z1(2)-z1(1)); 
!
! data :
! charge center :
 xcen=0.5d0*(${x0}+${x1});
 ycen=0.5d0*(${y0}+${y1});
 zcen=0.5d0*(${z0}+${z1});
!
 do i=1,$nx ; do j=1, $ny; do k=1, $nz
  drn=sqrt( (x2(i)-xcen)**2 + (y2(j)-ycen)**2 + (z2(k)-zcen)**2 )
! right-hand side :
  rhs(i,j,k)=-${Q}d0/(sqrt(2d0*pi)*${s})**3 * exp(-0.5d0*(drn/${s})**2) ;
! permittivity :
  eps(i,j,k)= ${eps0}d0*(${eout} + (${ein}-${eout})*ball(drn,rpad,s))
! compute exact solution by interpolation from phi
  drn=min(drn, r(npt-1))
  drn=max(drn, r(1))
  n = int(drn/dr) + 1
  a = (r(n+1)-drn)/dr
  b = 1d0-a
  u(i,j,k) = a*phi(n)+b*(phi(n+1))
 enddo;       enddo;       enddo
!
! write datafiles in chest format
!
 if ($qbin.eq.0) then ! ASCII
  open(1,file='uexact_test.dat',form='formatted', status='unknown')
  write(1,'(3I5)') $nx,$ny,$nz
  write(1,'(${nx}F30.15)') u
  close(1)
  open(1,file='rhs_test.dat',form='formatted', status='unknown')
  write(1,'(3I5)') $nx,$ny,$nz
  write(1,'(${nx}F30.15)') rhs
  close(1)
  open(1,file='eps_test.dat',form='formatted', status='unknown')
  write(1,'(3I5)') $nx,$ny,$nz
  write(1,'(${nx}F30.15)') eps
  close(1)
 else ! BINARY
  open(1,file='uexact_test.dat',form='unformatted', status='unknown')
  write(1) $nx,$ny,$nz
  write(1) u
  close(1)
  open(1,file='rhs_test.dat',form='unformatted', status='unknown')
  write(1) $nx,$ny,$nz
  write(1) rhs
  close(1)
  open(1,file='eps_test.dat',form='unformatted', status='unknown')
  write(1) $nx,$ny,$nz
  write(1) eps
  close(1)
 endif

 if ( ${useObjectBC}.eq.0 ) then ! do not need these if generating BCs from Object using Born/DH superposition
! bc arrays
 if ( ${useBornBC} > 0 ) then
 do k=1,$nz
  do j=1,$ny
   drn = sqrt( (${x0}d0-xcen)**2 + (y2(j)-ycen)**2 + (z2(k)-zcen)**2 )
   xbc0(j,k) = (1d0*${Q}) / (4*pi*${eps0}*${eout}) / drn
   drn = sqrt( (${x1}d0-xcen)**2 + (y2(j)-ycen)**2 + (z2(k)-zcen)**2 )
   xbc1(j,k) = (1d0*${Q}) / (4*pi*${eps0}*${eout}) / drn
  enddo
 enddo
!
 do k=1,$nz
  do i=1,$nx
   drn = sqrt( (x2(i)-xcen)**2 + (${y0}d0-ycen)**2 + (z2(k)-zcen)**2 )
   ybc0(i,k) = (1d0*${Q}) / (4*pi*${eps0}*${eout}) / drn
   drn = sqrt( (x2(i)-xcen)**2 + (${y1}d0-ycen)**2 + (z2(k)-zcen)**2 )
   ybc1(i,k) = (1d0*${Q}) / (4*pi*${eps0}*${eout}) / drn
  enddo
 enddo
!
 do j=1,$ny
  do i=1,$nx
   drn = sqrt( (x2(i)-xcen)**2 + (y2(j)-ycen)**2 + (${z0}d0-zcen)**2 )
   zbc0(i,j) = (1d0*${Q}) / (4*pi*${eps0}*${eout}) / drn
   drn = sqrt( (x2(i)-xcen)**2 + (y2(j)-ycen)**2 + (${z1}d0-zcen)**2 )
   zbc1(i,j) = (1d0*${Q}) / (4*pi*${eps0}*${eout}) / drn
  enddo
 enddo
!
 else ! exact analytical BCs
!
 do k=1,$nz
  do j=1,$ny
   drn = sqrt( (${x0}d0-xcen)**2 + (y2(j)-ycen)**2 + (z2(k)-zcen)**2 )
   drn=min(drn, r(npt-1))
   drn=max(drn, r(1))
   n = int(drn/dr) + 1
   a = (r(n+1)-drn)/dr
   b = 1d0-a
   xbc0(j,k) = a*phi(n)+b*(phi(n+1))
!
   drn = sqrt( (${x1}d0-xcen)**2 + (y2(j)-ycen)**2 + (z2(k)-zcen)**2 )
   drn=min(drn, r(npt-1))
   drn=max(drn, r(1))
   n = int(drn/dr) + 1
   a = (r(n+1)-drn)/dr
   b = 1d0-a
   xbc1(j,k) = a*phi(n)+b*(phi(n+1))
  enddo
 enddo
!
 do k=1,$nz
  do i=1,$nx
   drn = sqrt( (x2(i)-xcen)**2 + (${y0}d0-ycen)**2 + (z2(k)-zcen)**2 )
   drn=min(drn, r(npt-1))
   drn=max(drn, r(1))
   n = int(drn/dr) + 1
   a = (r(n+1)-drn)/dr
   b = 1d0-a
   ybc0(i,k) = a*phi(n)+b*(phi(n+1))
   drn = sqrt( (x2(i)-xcen)**2 + (${y1}d0-ycen)**2 + (z2(k)-zcen)**2 )
   drn=min(drn, r(npt-1))
   drn=max(drn, r(1))
   n = int(drn/dr) + 1
   a = (r(n+1)-drn)/dr
   b = 1d0-a
   ybc1(i,k) = a*phi(n)+b*(phi(n+1))
  enddo
 enddo
!
 do j=1,$ny
  do i=1,$nx
   drn = sqrt( (x2(i)-xcen)**2 + (y2(j)-ycen)**2 + (${z0}d0-zcen)**2 )
   drn=min(drn, r(npt-1))
   drn=max(drn, r(1))
   n = int(drn/dr) + 1
   a = (r(n+1)-drn)/dr
   b = 1d0-a
   zbc0(i,j) = a*phi(n)+b*(phi(n+1))
   drn = sqrt( (x2(i)-xcen)**2 + (y2(j)-ycen)**2 + (${z1}d0-zcen)**2 )
   drn=min(drn, r(npt-1))
   drn=max(drn, r(1))
   n = int(drn/dr) + 1
   a = (r(n+1)-drn)/dr
   b = 1d0-a
   zbc1(i,j) = a*phi(n)+b*(phi(n+1))
  enddo
 enddo
!
 endif ! bc
!
 open(10,file='xbc0_test.dat',form='formatted', status='unknown')
 open(11,file='xbc1_test.dat',form='formatted', status='unknown')
 open(12,file='ybc0_test.dat',form='formatted', status='unknown')
 open(13,file='ybc1_test.dat',form='formatted', status='unknown')
 open(14,file='zbc0_test.dat',form='formatted', status='unknown')
 open(15,file='zbc1_test.dat',form='formatted', status='unknown')
!
 write(10,'(F30.15)') xbc0(2:$ny-1,2:$nz-1); close(10)
 write(11,'(F30.15)') xbc1(2:$ny-1,2:$nz-1); close(11)
 write(12,'(F30.15)') ybc0(2:$nx-1,2:$nz-1); close(12)
 write(13,'(F30.15)') ybc1(2:$nx-1,2:$nz-1); close(13)
 write(14,'(F30.15)') zbc0(2:$nx-1,2:$ny-1); close(14)
 write(15,'(F30.15)') zbc1(2:$nx-1,2:$ny-1); close(15)
!
 endif ! useObjectBC
!
  contains
  function ball(dr, R, s)
! R : ball radius
! s : std of Gaussian filter
  float, parameter ::TOL=1d-13, sq2=sqrt(2d0), pi=4d0*atan(1d0)
  float :: ball
  float, intent(in) :: dr, R, s
!
  ball= 0.5d0 * ( erf( (dr+R)/s/sq2 ) - erf ( (dr-R)/s/sq2 ) );
! exponential term
  if (abs(dr)>TOL) then
   ball = ball + 1d0/sqrt(2*pi)*s/dr * ( exp ( -0.5d0*((dr+R)/s)**2 ) - exp ( -0.5d0*((dr-R)/s)**2 ) );
! note that the expression above will be divergent when dr is zero
! therefore, use a taylor expansion :
  else
   ball = ball - s/sqrt(2*pi)*exp(-0.5d0*(R**2+dr**2)/s**2)*( 2*R/s**2 + R**3/s**6*dr**2/3d0)
  endif
  end function ball
end " > test.F90
#
#echo $FC $FFLAGS $DEFS test.F90 -o test
$FC $FFLAGS $DEFS test.F90 -o test ; ./test; #rm -f test;
#exit
#
# write ion parameters to pqr file
# compute center :
xc=`echo "scale=6 ; 0.5*($x0 + $x1)" | bc`
yc=`echo "scale=6 ; 0.5*($y0 + $y1)" | bc`
zc=`echo "scale=6 ; 0.5*($z0 + $z1)" | bc`
echo -n "
REMARK SINGLE ION
PQR FORMAT
ATOM 1 Q ION 1 $xc $yc $zc ${Q} 0.00
" > born.pqr
#
rpad=`echo "$R + $pad" | bc -l `; # padded radius
# prepare input file for CHES
#
echo " Preparing input file..."
echo "\
!charmm
continuum {
#Size
 nx=${nx}; ny=${ny}; nz=${nz}

#Grid

 xgrid=exp; xstretch=${xstretch}; x0=${x0}; x1=${x1}
 ygrid=exp; ystretch=${ystretch}; y0=${y0}; y1=${y1}
 zgrid=exp; zstretch=${zstretch}; z0=${z0}; z1=${z1}

#Continuum output options
! output_format=plot3d
 output_format=chest
 output_mode=${IOMODE}
 gridoutput=xyz_test.xyz

 exec:output
}

#Communicators
multicom {
 exec:set ches 1
}

object {
 object=molecule
}

molecule {
 structype=PQR ! note : would be good to have multple ways/keywords of specifying
 structure=born.pqr ! note that this file should have a single charge with radius 0 (unit mass)
 kappa_solute=0 ! note that could skip gaussian gridding if solute/solvent values are same
 kappa_solvent=0
 eps_solute=${ein}
 eps_solvent=${eout}
 eps_scale=${eps0}
# eps_scale=charmm
 eps_padding=${rpad} ! this is added to the radius to compute the eps array
 charge_padding=0 ! added to radius to compute smoothed right-hand-side
 stdev_eps=${s} ! might be worthwhile to be able to set a single stdev
 stdev_charge=${s}
 cutoff_eps_stdev=6
 cutoff_charge_stdev=6
}

ches {
# BC
" > test.dat
if [ ${useObjectBC} -eq 1 ]; then
echo "\
 phi_bcx0=object
 phi_bcx1=object
 phi_bcy0=object
 phi_bcy1=object
 phi_bcz0=object
 phi_bcz1=object
" >> test.dat
else # use precomputed arrays
echo "\
 phi_bcx0=dirichlet; phi_bcx0_file=xbc0_test.dat
 phi_bcx1=dirichlet; phi_bcx1_file=xbc1_test.dat
 phi_bcy0=dirichlet; phi_bcy0_file=ybc0_test.dat
 phi_bcy1=dirichlet; phi_bcy1_file=ybc1_test.dat
 phi_bcz0=dirichlet; phi_bcz0_file=zbc0_test.dat
 phi_bcz1=dirichlet; phi_bcz1_file=zbc1_test.dat
" >> test.dat
fi
#continue with the rest of inout file
echo "\
#Initial 3D data

! epsinit=object
 epsinit=const ; epsconst=${eps0}
! epsinit=file ; epsfile=eps_test.dat ; eps_mode=text ; eps_format=chest
 kappainit=constant ; kappaconst=0.
 rhsinit=object
! rhsinit=file ; rhsfile=rhs_test.dat ; rhs_mode=text ; rhs_format=chest
 phiinit=constant   ; phiconst=0. % initial solution

#Solver
 solver=multigrid

#Output
 output_format=chest
 output_mode=${IOMODE}
 phioutput=solution.dat
# epsoutput=eps.dat
 rhsoutput=rhs.dat

#Execution
 exec:init
 exec:solve
 exec:output
 exec:done
} ! ches

multigrid {
# multigrid solver parameters
# multigrid_maximum_cycles=4
 multigrid_smooth_iterations=5
# multigrid_maximum_levels=4
# multigrid_smoother=Gauss-Seidel-CUDA
 multigrid_smoother=Jacobi
# multigrid_smoother=Gauss-Seidel
# multigrid_residual=2e-4 # for shorter running times
 multigrid_residual=1.5e-4
# multigrid_smoother=Jacobi-Tiled-LM
# multigrid_compute_ini_residual=no
# multigrid_skip_convergence_test=3
# multigrid_smoother_unroll=-1
# multigrid_omega=$omega
}

" >> test.dat
if !([ -L ches ]); then
ln -s ../ches .
fi
echo " Running CHES..."
#echo " ********************************************************************************************"
ulimit -s unlimited
./ches < test.dat #>/dev/null
#
# compare solutions
#
echo " Comparing to analytical solution..."
#echo " ********************************************************************************************"
#
echo "
 implicit none
 float, dimension($nx,$ny,$nz)  :: uanl, uches, rhs
 float :: grid($nx,$ny,$nz,3)
 float :: x1($nx), x2($nx), y1($ny), y2($ny), z1($nz), z2($nz)
 float :: griderror, error, totq, dx, dy, dz, urms, pote
 integer :: where(3), i, j, k
!
! compare grids
!
 open(1,file='xg_test.dat',form='formatted', status='old')
 read(1,*) x1
 close(1)
 open(1,file='yg_test.dat',form='formatted', status='old')
 read(1,*) y1
 close(1)
 open(1,file='zg_test.dat',form='formatted', status='old')
 read(1,*) z1
 close(1)
! bring grids to center
 x2(2:$nx)=0.5d0*(x1(1:$nx-1)+x1(2:$nx)); x2(1)=x1(1)-0.5d0*(x1(2)-x1(1)); x1=x2;
 y2(2:$ny)=0.5d0*(y1(1:$ny-1)+y1(2:$ny)); y2(1)=y1(1)-0.5d0*(y1(2)-y1(1)); y1=y2;
 z2(2:$nz)=0.5d0*(z1(1:$nz-1)+z1(2:$nz)); z2(1)=z1(1)-0.5d0*(z1(2)-z1(1)); z1=z2;
!
! grid output from CHEST is at center
!
 if (${qbin}.eq.0) then
  open(1,file='xyz_test.xyz',form='formatted', status='old')
  read(1,*)
!  read(1,*) grid ! plot3d
  read(1,*) x2, y2, z2 ! chest
 else
  open(1,file='xyz_test.xyz',form='unformatted', status='old')
  read(1)
!  read(1) grid ! plot3d
  read(1) x2, y2, z2 ! chest
 endif
 close(1)
!
! x2=grid(:,1,1,1); y2=grid(1,:,1,2); z2=grid(1,1,:,3) ! plot3d
 griderror=max(maxval(abs(x1-x2)), maxval(abs(y1-y2)), maxval(abs(z1-z2)))
! write(0,*) x1-x2
! write(0,*) y1-y2
! write(0,*) z1-z2
!
! compare solutions
!
 if (${qbin}.eq.0) then
  open(1,file='uexact_test.dat',form='formatted', status='old')
  read(1,*)
  read(1,*) uanl
  close(1)
!
  open(1,file='solution.dat',form='formatted', status='old')
  read(1,*)
  read(1,*) uches
  close(1)
! read rhs file to compute potential energy :
  open(1,file='rhs.dat',form='formatted', status='old')
  read(1,*)
  read(1,*) rhs
  close(1)
 else
  open(1,file='uexact_test.dat',form='unformatted', status='old')
  read(1)
  read(1) uanl
  close(1)
!
  open(1,file='solution.dat',form='unformatted', status='old')
  read(1)
  read(1) uches
  close(1)
!
  open(1,file='rhs.dat',form='unformatted', status='old')
  read(1)
  read(1) rhs
  close(1)
 endif
!
 pote=0d0;
 totq=0d0;
 urms=0d0;
! integrate for nonuniform mesh
 do k=2,$nz-1 ; dz=(z1(k)-z1(k-1))
  do j=2,$ny-1 ; dy=(y1(j)-y1(j-1))*dz
   do i=2,$nx-1 ; dx=(x1(i)-x1(i-1))*dy
    pote = pote + uches(i,j,k) * rhs(i,j,k) * dx
!    pote = pote + uanl(i,j,k) * rhs(i,j,k) * dx
    totq = totq + rhs(i,j,k) * dx
!    urms = urms + uanl(i,j,k)**2 * dx
    urms = urms + uches(i,j,k)**2 * dx
 enddo ; enddo ; enddo
 pote=0.5d0 * pote
 totq=-totq
 urms=sqrt(urms)
!
 uanl=abs(uanl-uches);
 error=maxval(uanl(2:$nx-1,2:$ny-1,2:$nz-1))
 where=maxloc(uanl(2:$nx-1,2:$ny-1,2:$nz-1))
!
 write(6,'(2F25.12,3I10)') griderror, error, where
! RMS error :
 error=sqrt ( sum ( uanl(2:$nx-1,2:$ny-1,2:$nz-1)**2 ) / (( $nx-2 )*( $ny-2 )*( $nz-2 )) )
 write(6,'(F25.12)') error
!
 write(6,'(F25.12)') pote
 write(6,'(F25.12)') totq
 write(6,'(F25.12)') urms
 end " > compare.F90
#
#echo $FC $FFLAGS $DEFS compare.F90 -o compare
$FC $FFLAGS $DEFS compare.F90 -o compare
#exit
j=0
for f in `./compare`; do
 i[$j]=$f
 j=$(($j+1))
done
rm -f compare;
griderr=0.00001;
if [ `echo "${i[0]} > $griderr" | bc` -eq 1 ]; then
 echo " Grids do not match!";
 echo " TEST FAILED";
 test_passed=0
else
 ermax=0.06; # ad-hoc criterion
 echo " The electrostatic energy is ${i[6]}"
 echo " Total charge is ${i[7]}"
 echo " The absolute RMS error is ${i[5]}"
 echo " The relative RMS error is ${i[5]} / ${i[8]} = `echo ${i[5]}/${i[8]} |bc -l`"
 echo " The maximum absolute error is "${i[1]}" at grid point ["${i[2]}","${i[3]}","${i[4]}"]"
 echo " Comparing with maximum allowed error ("$ermax")"
 if [ `echo "${i[5]} < $ermax" | bc` -eq 1 ]; then
  echo " TEST PASSED";
  test_passed=1
 else
  echo " TEST FAILED";
  test_passed=0
 fi
fi
echo " ********************************************************************************************"
#
# clean up
#
#if [ -L ches ]; then
# rm -f ches ; 
#fi
#
exit $test_passed
